image: atlassian/default-image:2

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          # declare vars
          - export IMAGE_NAME=quaide/dem
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER .       
          # authenticate with the Docker Hub registry
          - docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
          # push the new tag to repo
          - docker push $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER
          # create a latest tag as well
          - docker tag $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER $IMAGE_NAME:latest
          # push latest tag to repo
          - docker push $IMAGE_NAME:latest
          
          #### QUAY
          # declare vars
          - export IMAGE_NAME=quay.io/fivium/dem
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER .       
          # authenticate with the Quay registry
          - docker login -u=$QUAY_USERNAME -p=$QUAY_PASSWORD quay.io
          # push the new tag to repo
          - docker tag $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER $IMAGE_NAME:latest-auto-$BITBUCKET_BUILD_NUMBER
          - docker push $IMAGE_NAME:latest-auto-$BITBUCKET_BUILD_NUMBER
          # create a latest tag as well
          - docker tag $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER $IMAGE_NAME:latest
          # push latest tag to repo
          - docker push $IMAGE_NAME:latest

          #### QUAY scratch
          # declare vars
          - export IMAGE_NAME=quay.io/fivium/dem
          # build the Docker image
          - docker build -f Dockerfile-scratch -t $IMAGE_NAME:scratch-$BITBUCKET_BUILD_NUMBER .       
          # authenticate with the Quay registry
          - docker login -u=$QUAY_USERNAME -p=$QUAY_PASSWORD quay.io
          # push the new tag to repo
          - docker tag $IMAGE_NAME:scratch-$BITBUCKET_BUILD_NUMBER $IMAGE_NAME:scratch-auto-$BITBUCKET_BUILD_NUMBER
          - docker push $IMAGE_NAME:scratch-auto-$BITBUCKET_BUILD_NUMBER
          # # create a latest tag as well
          # - docker tag $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER $IMAGE_NAME:latest
          # # push latest tag to repo
          # - docker push $IMAGE_NAME:latest