FROM python:3-slim as build
COPY app/ /app/
WORKDIR /app/
RUN apt update && apt-get install -y -y libc-bin binutils build-essential patchelf \
    && pip3 install pyYaml docker six pyinstaller staticx \
    && pyinstaller /app/main.py --onefile \
    && staticx /app/dist/main dem

FROM scratch
WORKDIR /app/
COPY --from=build /app/dem /app/dem
COPY --from=build /tmp /tmp
CMD ["/app/dem"]
